# agent.py
import random

class RLAgent:
    def __init__(self):
        # Initialize your CNN, Q-Table, or Actor-Critic networks here
        pass

    def get_action(self, state, valid_moves, info):
        """
        state: 6x7 numpy array of the board
        valid_moves: list of integers representing non-full columns (e.g., [0, 1, 2, 4, 5, 6])
        info: Dictionary containing extracted features (center_control, threats, etc.)
        """
        # TODO: Pass 'state' through your CNN or logic here
        
        # For now, it just plays a random valid move
        print(f"Agent sees features: {info}")
        return random.choice(valid_moves)

    def train_step(self, state, action, reward, next_state, done):
        """
        Call this during your training loop to update your network weights
        using the rewards generated by the engine.
        """
        # TODO: Implement backpropagation or Q-value updating here
        pass



'''How to use this workflow:
Design your AI: Open agent.py. Build your PyTorch CNN or standard Q-table inside the __init__ method.

Write a Headless Training Script (Optional): If you are doing Reinforcement Learning, you'll want to train the agent without the UI turning on, so it can play 10,000 games in a few minutes. You can import Connect4Env from connect4_engine.py in a separate script and just loop through the environment steps rapidly.

Test it Live: Once your agent is trained (or even before, just to watch it play randomly), simply run python connect4_engine.py. The Pygame window will pop up. You will play as Red (click to drop), and your custom RL algorithm will respond as Yellow.
'''